version: "2"
services:
        nodeserver:
                container_name: backendapplication
                build:
                        context: ./app
                ports:
                        - "5000:5000"
        nginix:
                container_name: nginx
                restart: always
                build:
                        context: ./nginx
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                        - ./nginx/error.log:/etc/nginx/error_log.log
                        - ./certbot/conf:/etc/letsencrypt
                        - ./certbot/www:/var/www/certbot
        certbot:
                container_name: certbot
                image: certbot/certbot
                volumes: 
                        - ./certbot/conf:/etc/letsencrypt
                        - ./certbot/www:/var/www/certbot
                command: certonly --webroot -w /var/www/certbot --force-renewal --email parthramnathpur0546@gmail.com - d tradekit.pro --agree-tos